import { SR_EVENT_EMITTER_TYPES } from '../../features/session_replay/constants'
import { API_ACTION_TEXT_CALLED, API_ADD_PAGE_ACTION_CALLED, API_ADD_RELEASE_CALLED, API_ADD_TO_TRACE_CALLED, API_END_CALLED, API_FINISHED_CALLED, API_GET_CALLED, API_GET_CONTEXT_CALLED, API_IGNORE_CALLED, API_INTERACTION_CALLED, API_NOTICE_ERROR_CALLED, API_ON_END_CALLED, API_PAUSE_REPLAY_CALLED, API_RECORD_REPLAY_CALLED, API_ROUTE_NAME_CALLED, API_SAVE_CALLED, API_SET_APPLICATION_VERSION_CALLED, API_SET_ATTRIBUTE_CALLED, API_SET_CURRENT_ROUTE_NAME_CALLED, API_SET_CUSTOM_ATTRIBUTE_CALLED, API_SET_ERROR_HANDLER_CALLED, API_SET_NAME_CALLED, API_SET_PAGE_VIEW_NAME_CALLED, API_SET_USER_ID_CALLED } from '../../features/utils/supportability-metrics'

export const SET_ERROR_HANDLER = 'setErrorHandler'
export const FINISHED = 'finished'
export const ADD_TO_TRACE = 'addToTrace'
export const ADD_RELEASE = 'addRelease'
export const ADD_PAGE_ACTION = 'addPageAction'
export const SET_CURRENT_ROUTE_NAME = 'setCurrentRouteName'
export const SET_PAGE_VIEW_NAME = 'setPageViewName'
export const SET_CUSTOM_ATTRIBUTE = 'setCustomAttribute'
export const INTERACTION = 'interaction'
export const NOTICE_ERROR = 'noticeError'
export const SET_USER_ID = 'setUserId'
export const SET_APPLICATION_VERSION = 'setApplicationVersion'
export const START = 'start'
export const ROUTE_NAME = 'routeName'

export const ACTION_TEXT = 'actionText'
export const SET_NAME = 'setName'
export const SET_ATTRIBUTE = 'setAttribute'
export const SAVE = 'save'
export const IGNORE = 'ignore'
export const ON_END = 'onEnd'
export const GET_CONTEXT = 'getContext'
export const END = 'end'
export const GET = 'get'

export const apiMethods = [
  SET_ERROR_HANDLER, FINISHED, ADD_TO_TRACE, ADD_RELEASE,
  ADD_PAGE_ACTION, SET_CURRENT_ROUTE_NAME, SET_PAGE_VIEW_NAME, SET_CUSTOM_ATTRIBUTE,
  INTERACTION, NOTICE_ERROR, SET_USER_ID, SET_APPLICATION_VERSION, START,
  SR_EVENT_EMITTER_TYPES.RECORD, SR_EVENT_EMITTER_TYPES.PAUSE
]

export const asyncApiMethods = [
  SET_ERROR_HANDLER, FINISHED, ADD_TO_TRACE, ADD_RELEASE
]

export const apiSMs = {
  [SET_ERROR_HANDLER]: API_SET_ERROR_HANDLER_CALLED,
  [FINISHED]: API_FINISHED_CALLED,
  [ADD_TO_TRACE]: API_ADD_TO_TRACE_CALLED,
  [ADD_RELEASE]: API_ADD_RELEASE_CALLED,
  [ADD_PAGE_ACTION]: API_ADD_PAGE_ACTION_CALLED,
  [SET_CURRENT_ROUTE_NAME]: API_SET_CURRENT_ROUTE_NAME_CALLED,
  [SET_PAGE_VIEW_NAME]: API_SET_PAGE_VIEW_NAME_CALLED,
  [SET_CUSTOM_ATTRIBUTE]: API_SET_CUSTOM_ATTRIBUTE_CALLED,
  [INTERACTION]: API_INTERACTION_CALLED,
  [NOTICE_ERROR]: API_NOTICE_ERROR_CALLED,
  [SET_USER_ID]: API_SET_USER_ID_CALLED,
  [SET_APPLICATION_VERSION]: API_SET_APPLICATION_VERSION_CALLED,
  [SR_EVENT_EMITTER_TYPES.RECORD]: API_RECORD_REPLAY_CALLED,
  [SR_EVENT_EMITTER_TYPES.PAUSE]: API_PAUSE_REPLAY_CALLED,
  [ROUTE_NAME]: API_ROUTE_NAME_CALLED,
  [ACTION_TEXT]: API_ACTION_TEXT_CALLED,
  [SET_NAME]: API_SET_NAME_CALLED,
  [SET_ATTRIBUTE]: API_SET_ATTRIBUTE_CALLED,
  [SAVE]: API_SAVE_CALLED,
  [IGNORE]: API_IGNORE_CALLED,
  [ON_END]: API_ON_END_CALLED,
  [GET_CONTEXT]: API_GET_CONTEXT_CALLED,
  [END]: API_END_CALLED,
  [GET]: API_GET_CALLED
}
