name: CI container setup
descriptions: Setup the CI container with latest NodeJS LTS version

runs:
  using: "composite"
  steps:
    - name: Setup Container
      run: apt update && apt install -y git
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
