export const VITAL_NAMES = {
  FIRST_PAINT: 'FP',
  FIRST_CONTENTFUL_PAINT: 'fcp',
  FIRST_INPUT_DELAY: 'fi',
  LARGEST_CONTENTFUL_PAINT: 'lcp',
  CUMULATIVE_LAYOUT_SHIFT: 'cls',
  INTERACTION_TO_NEXT_PAINT: 'inp',
  LONG_TASK: 'LT',
  TIME_TO_FIRST_BYTE: 'ttfb'
}
