# This composite action is used run repository updates post production release
# like updating the caniuse dependency and integration testing
# browsers for the project.

name: 'Post Release Updates'

inputs:
  github_login:
    description: 'Github login associated with github authentication token.'
    required: true
  github_token:
    description: "The github token to use for interacting with the repositories."
    required: true
  github_email:
    description: 'Email address associated with github login user.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install --silent --no-progress --prefix $GITHUB_ACTION_PATH/..
      shell: bash
    - name: Run action script
      id: action-script
      run: |
        node $GITHUB_ACTION_PATH/index.js \
          --open-pull-request \
          --github-login ${{ inputs.github_login }} \
          --github-token ${{ inputs.github_token }} \
          --github-email ${{ inputs.github_email }}
      shell: bash
