import { getCanonicalModelPaths } from './config-model-reader.js'

/**
 * Maps a NerdGraph browser-settings field (dotted path, rooted at the
 * settings object generated by settings-generator.js, e.g.
 * "sessionReplay.samplingRate") to where it should land in this repo's
 * browser-agent init/info/loader_config models (dotted path, e.g.
 * "init.session_replay.sampling_rate").
 *
 * `agentPath: null` means "confirmed this field is NOT expected to appear
 * in the injected snippet at all" (has a `reason`). Any NerdGraph field
 * settings-generator.js can set that is missing from this map entirely is
 * an unreviewed TODO, not a confirmed non-mapping - report.js treats those
 * as gaps needing triage same as an explicit null entry, but callers should
 * extend this map rather than leaving fields implicit.
 *
 * Derived from a live introspection of AgentApplicationSettingsUpdateInput
 * against staging-api.newrelic.com/graphql plus a direct read of
 * src/common/config/{info,init,loader-config}.js, both done as part of
 * planning this action - NOT verified against real end-to-end data yet
 * (see the plan's Open risks / Verification). Expect to correct entries,
 * especially the "possible gap" ones, once this runs for real.
 */
export const NERDGRAPH_TO_AGENT_MAP = {
  'browserConfig.apdexTarget': { agentPath: null, reason: 'Apdex target is a server-side scoring threshold, not delivered to the injected snippet.' },

  'browserConsentMode.enabled': { agentPath: 'init.browser_consent_mode.enabled' },

  'browserLogging.enabled': { agentPath: 'init.logging.enabled' },
  'browserLogging.level': { agentPath: null, reason: 'POSSIBLE GAP: no log-level field under init.logging; needs confirmation whether level filtering is server-side only.' },
  'browserLogging.samplingRate': { agentPath: null, reason: 'POSSIBLE GAP: no sampling_rate field under init.logging currently.' },
  'browserLogging.manualLogs.enabled': { agentPath: null, reason: 'POSSIBLE GAP: no manual-logs sub-config under init.logging currently.' },
  'browserLogging.manualLogs.level': { agentPath: null, reason: 'POSSIBLE GAP: see browserLogging.manualLogs.enabled.' },
  'browserLogging.manualLogs.samplingRate': { agentPath: null, reason: 'POSSIBLE GAP: see browserLogging.manualLogs.enabled.' },

  'browserMonitoring.ajax.capturePayloads': { agentPath: 'init.ajax.capture_payloads' },
  'browserMonitoring.ajax.denyList': { agentPath: 'init.ajax.deny_list' },
  'browserMonitoring.api.register.enabled': { agentPath: 'init.api.register.enabled' },
  'browserMonitoring.api.register.duplicateDataToContainer': { agentPath: 'init.api.register.duplicate_data_to_container' },
  'browserMonitoring.api.register.allowIframeBridge': { agentPath: 'init.api.register.allow_iframe_bridge' },
  'browserMonitoring.api.register.iframeDomains': { agentPath: 'init.api.register.iframe_domains' },
  'browserMonitoring.distributedTracing.enabled': { agentPath: 'init.distributed_tracing.enabled' },
  'browserMonitoring.distributedTracing.corsEnabled': { agentPath: null, reason: 'POSSIBLE GAP: init.distributed_tracing has only the specific cors_use_* toggles, no generic cors-enabled field.' },
  'browserMonitoring.distributedTracing.corsUseNewrelicHeader': { agentPath: 'init.distributed_tracing.cors_use_newrelic_header' },
  'browserMonitoring.distributedTracing.corsUseTracecontextHeaders': { agentPath: 'init.distributed_tracing.cors_use_tracecontext_headers' },
  'browserMonitoring.distributedTracing.excludeNewrelicHeader': { agentPath: 'init.distributed_tracing.exclude_newrelic_header' },
  'browserMonitoring.distributedTracing.allowedOrigins': { agentPath: 'init.distributed_tracing.allowed_origins' },
  'browserMonitoring.loader': { agentPath: null, reason: 'Selects which loader variant (full/spa/lite) the collector renders - a property of the snippet itself, not a field inside it.' },
  'browserMonitoring.pinnedVersion': { agentPath: null, reason: "Controls which agent version the snippet's async tag points at, not an init field." },
  'browserMonitoring.privacy.cookiesEnabled': { agentPath: 'init.privacy.cookies_enabled' },

  'browserObfuscation.rules.regex': { agentPath: 'init.obfuscate' },
  'browserObfuscation.rules.replacement': { agentPath: 'init.obfuscate' },
  'browserObfuscation.rules.eventFilter': { agentPath: null, reason: 'POSSIBLE GAP: init.obfuscate rule entries have no eventFilter field currently.' },

  'browserPerformance.captureDetail': { agentPath: 'init.performance.capture_detail' },
  'browserPerformance.captureMarks': { agentPath: 'init.performance.capture_marks' },
  'browserPerformance.captureMeasures': { agentPath: 'init.performance.capture_measures' },

  'browserWebSockets.enabled': { agentPath: 'init.web_sockets.enabled' },

  'sessionReplay.enabled': { agentPath: 'init.session_replay.enabled' },
  'sessionReplay.autoStart': { agentPath: 'init.session_replay.autoStart' },
  'sessionReplay.preload': { agentPath: 'init.session_replay.preload' },
  'sessionReplay.samplingRate': { agentPath: 'init.session_replay.sampling_rate' },
  'sessionReplay.errorSamplingRate': { agentPath: 'init.session_replay.error_sampling_rate' },
  'sessionReplay.blockSelector': { agentPath: 'init.session_replay.block_selector' },
  'sessionReplay.collectFonts': { agentPath: 'init.session_replay.collect_fonts' },
  'sessionReplay.fixStylesheets': { agentPath: 'init.session_replay.fix_stylesheets' },
  'sessionReplay.inlineImages': { agentPath: 'init.session_replay.inline_images' },
  'sessionReplay.inlineStylesheet': { agentPath: null, reason: 'POSSIBLE GAP: init.session_replay has inline_images but no analogous inline_stylesheet(s) field.' },
  'sessionReplay.maskAllInputs': { agentPath: 'init.session_replay.mask_all_inputs' },
  // settings-generator.js recurses into maskInputOptions and generates one
  // leaf fieldPath per input-type key (confirmed live, 2026-09-04) rather
  // than a single "maskInputOptions" path - all of them land under the same
  // parent object in init.js. UNVERIFIED CASING ASSUMPTION: this maps to
  // the camelCase key as-is (e.g. datetimeLocal), but init.js's real model
  // uses kebab-case ('datetime-local') and lowercase (textarea, select) -
  // see config-model-reader.js's comment on this same object. session_replay
  // never appeared in this action's one successful live run, so which
  // casing the rendered snippet actually uses is unconfirmed either way -
  // fix this mapping (and possibly config-model-reader.js's shape) once a
  // live run actually populates session_replay.
  ...Object.fromEntries(
    ['color', 'date', 'datetimeLocal', 'email', 'month', 'number', 'range', 'search', 'select', 'tel', 'text', 'textArea', 'time', 'url', 'week']
      .map(key => [`sessionReplay.maskInputOptions.${key}`, { agentPath: `init.session_replay.mask_input_options.${key}` }])
  ),
  'sessionReplay.maskTextSelector': { agentPath: 'init.session_replay.mask_text_selector' },

  'sessionTrace.enabled': { agentPath: 'init.session_trace.enabled' },
  'sessionTrace.errorSamplingRate': { agentPath: null, reason: 'POSSIBLE GAP: init.session_trace only has enabled/autoStart currently, no sampling fields.' },
  'sessionTrace.mode': { agentPath: null, reason: 'POSSIBLE GAP: see sessionTrace.errorSamplingRate.' },
  'sessionTrace.samplingRate': { agentPath: null, reason: 'POSSIBLE GAP: see sessionTrace.errorSamplingRate.' }
}

// Agent-model paths (see config-model-reader.js) that are known to have no
// NerdGraph settings counterpart *by design*, with a reason - anything in
// the canonical model that is NEITHER here NOR a mapping target above is
// reported as an unreviewed capability gap by report.js's bucket (4).
const INIT_INTENTIONALLY_UNMAPPED = {
  'init.ajax.block_internal': 'Hardcoded internal-NR-domain exclusion; not an account setting.',
  'init.feature_flags': 'Internal experimental feature-flag list, not an account-configurable setting.',
  'init.proxy.assets': 'Deployment-time asset-proxy override, not an account/entity setting.',
  'init.proxy.beacon': 'Deployment-time beacon-proxy override, not an account/entity setting.',
  'init.session_replay.block_class': 'Hardcoded enforced CSS class constant (nr-block), read-only getter in init.js.',
  'init.session_replay.ignore_class': 'Hardcoded enforced CSS class constant (nr-ignore), read-only getter in init.js.',
  'init.session_replay.mask_text_class': 'Hardcoded enforced CSS class constant (nr-mask), read-only getter in init.js.',
  'init.ssl': 'Legacy/deprecated field, not present anywhere in the NerdGraph browser settings schema.'
}

const IDENTITY_REASON = 'Identity/account-linkage field populated from the account & application record itself, not a browser-monitoring setting - no corresponding NerdGraph *settings* mutation field is expected.'

export function getAgentFieldsIntentionallyUnmapped () {
  const canonical = getCanonicalModelPaths()
  const result = { ...INIT_INTENTIONALLY_UNMAPPED }

  for (const p of canonical.info) result[`info.${p}`] = IDENTITY_REASON
  for (const p of canonical.loaderConfig) result[`loaderConfig.${p}`] = IDENTITY_REASON

  return result
}
