# This composite action is used to notify an external repository of an event
# using the repository_dispatch trigger

name: 'Notify Repository'

inputs:
  token:
    description: 'GH Personal Access Token'
    required: true
  repo_owner:
    description: 'Repository Owner'
    required: true
  repo_name:
    description: 'Repository Name'
    required: false
  event_type:
    description: "Event type expected by recipient"
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify ${{ inputs.repo_name }}
      id: action-script
      run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.repo_owner }}/${{ inputs.repo_name }}/dispatches \
          -d '{"event_type":"${{ inputs.event_type }}"}'
      shell: bash
