# This action is used to bump a new prerelease version and publish that version to NPM.

name: Prerelease NPM Version

inputs:
  preid:
    description: "The prerelease identifier to use for the version number when bumping a prerelease version."
    type: string
    required: true
    default: rc
  version-override:
    description: "If not supplied, the version in package.json will be used. Whichever version is greater between local and NPM will take precedence -- we can only create prerelease versions *ahead* of the current version in NPM."
    type: string
    required: false
  dry_run:
    description: "Indicates whether to dry run the npm publish command."
    type: boolean
    required: false
    default: 'false'

outputs:
  version:
    description: "The new version number after bumping a prerelease version."
    value: ${{ steps.bump-prerelease.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install --silent --no-progress --prefix $GITHUB_ACTION_PATH/..
      shell: bash
    - name: Get version number
      id: agent-loader-version
      shell: bash
      run: echo "results=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
    - name: Bump prerelease version
      id: bump-prerelease
      shell: bash
      run: |
        node $GITHUB_ACTION_PATH/index.cjs \
          --version-override ${{ inputs.version-override }} \
          --preid ${{ inputs.preid }}
    - name: Install project dependencies
      shell: bash
      run: npm ci
    - name: Build npm package
      shell: bash
      run: npm run build:npm
    - name: Publish npm package
      shell: bash
      run: npm publish ${{ ((inputs.dry_run == true || inputs.dry_run == 'true') && '--dry-run') || '' }} --tag=${{ inputs.preid }}
