name: 'Docs PR'
description: >
  This composite action constructs and opens a pull request on the
  docs website repository.

inputs:
  tag:
    description: "Name of the tag to pull the release information for."
    required: true
  github_login:
    description: 'Github login associated with github authentication token.'
    required: true
  github_email:
    description: 'Email address associated with github login user.'
    required: true
  nr_docs_github_token:
    description: 'New Relic github org authentication token scoped to the docs repo'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install --silent --no-progress --prefix $GITHUB_ACTION_PATH/..
      shell: bash
    - name: Run action script
      id: action-script
      run: |
        node $GITHUB_ACTION_PATH/index.js \
          --tag ${{ inputs.tag }} \
          --github-login ${{ inputs.github_login }} \
          --github-email ${{ inputs.github_email }} \
          --nr-docs-github-token ${{ inputs.nr_docs_github_token }}
      shell: bash
