#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

# enable colored output in terminal
export FORCE_COLOR=1

npm run lint
npm run test -- --onlyChanged
npm run npm:build:types && npm run test:types