# This workflow is used to manually bump a new prerelease version and publish to NPM.
# The prerelease-npm-version action in this workflow is called on each main branch push with the "rc" preid and tag.

name: Prerelease NPM Version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "The type of version bump to make. One of: major, minor, patch, premajor, preminor, prepatch, or prerelease."
        type: choice
        required: true
        default: preminor
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
          - from-git
      preid:
        description: "The prerelease identifier to use when bumping a prerelease version."
        type: string
        required: true
        default: rc
      tag:
        description: "The NPM package distribution tag to use when publishing the prerelease."
        type: string
        required: true
        default: rc
      dry_run:
        description: "Indicates whether to dry run the npm publish command."
        type: boolean
        required: true

jobs:
  prerelease-npm-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prerelease-npm-version.outputs.results }}
    env:
      NPM_TOKEN: ${{ secrets.BROWSER_NPM_TOKEN }}
      GITHUB_LOGIN: ${{ secrets.BROWSER_GITHUB_BOT_NAME }}
      GITHUB_EMAIL: ${{ secrets.BROWSER_GITHUB_BOT_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0 # See package.json for the stable node version that works with our testing.  Do not change this unless you know what you are doing as some node versions do not play nicely with our testing server.
      - name: Authenticate npm
        shell: bash
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - name: Set up git
        id: git-setup
        run: |
          git config --global user.name "${GITHUB_LOGIN}"
          git config --global user.email "${GITHUB_EMAIL}"
      - uses: ./.github/actions/prerelease-npm-version
        id: prerelease-npm-version
        with:
          version-type: ${{ github.event.inputs.version-type }}
          preid: ${{ github.event.inputs.preid }}
          tag: ${{ github.event.inputs.tag }}
          dry_run: ${{ github.event.inputs.dry_run }}
