# This workflow is used to manually bump a new prerelease version and publish to NPM.
# The prerelease-npm-version action in this workflow is called on each main branch push with the "rc" preid and tag.

name: Prerelease NPM Version

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "The prerelease identifier to use when bumping a prerelease version."
        type: string
        required: true
        default: rc
      version-override:
        description: "If not supplied, the version in package.json will be used. Whichever version is greater between local and NPM will take precedence -- we can only create prerelease versions *ahead* of the current version in NPM."
        type: string
        required: false
      dry_run:
        description: "Indicates whether to dry run the npm publish command."
        type: boolean
        required: false
        default: "false"

jobs:
  prerelease-npm-version:
    uses: ./.github/workflows/npm-operations.yml
    with:
      operation: publish-prerelease
      preid: ${{ github.event.inputs.preid }}
      version-override: ${{ github.event.inputs.version-override }}
      dry_run: ${{ github.event.inputs.dry_run == 'true' }}
    secrets:
      NPM_TOKEN: ${{ secrets.BROWSER_NPM_TOKEN }}
      GITHUB_LOGIN: ${{ secrets.BROWSER_GITHUB_BOT_NAME }}
      GITHUB_EMAIL: ${{ secrets.BROWSER_GITHUB_BOT_EMAIL }}
