name: Build and Deploy to NR Internal Prod

on:
  workflow_dispatch:
    inputs:
      current:
        description: 'CURRENT "stable" version number (must be published to CDN root)'
        required: true
      next:
        description: 'NEXT version number (must be published to CDN root)'
        required: true

jobs:
  publish-build:
    runs-on: ubuntu-latest
    container: node:14
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: check files
        run: |
          node ./tools/scripts/check-file.js \
            -p https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.current }}.min.js \
            -p https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.next }}.min.js 
      - name: re-publish internal loader (prod)
        run: |
          node ./tools/scripts/upload-ab-to-s3.js \
            --env prod \
            --current https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.current }}.min.js \
            --next https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.next }}.min.js \
            --appId ${{ secrets.INTERNAL_PRODUCTION_APPLICATION_ID }} \
            --licenseKey ${{ secrets.INTERNAL_LICENSE_KEY }} \
            --bucket ${{ secrets.AWS_BUCKET }} \
            --sha $GITHUB_SHA \
            --workflow $GITHUB_WORKFLOW \
            --role ${{ secrets.AWS_ROLE_ARN }}
      - name: re-publish internal loader (eu-prod)
        run: |
          node ./tools/scripts/upload-ab-to-s3.js \
            --env eu-prod \
            --current https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.current }}.min.js \
            --next https://js-agent.newrelic.com/nr-loader-spa-${{ github.event.inputs.next }}.min.js \
            --appId ${{ secrets.INTERNAL_EU_PRODUCTION_APPLICATION_ID }} \
            --licenseKey ${{ secrets.INTERNAL_LICENSE_KEY }} \
            --bucket ${{ secrets.AWS_BUCKET }} \
            --sha $GITHUB_SHA \
            --workflow $GITHUB_WORKFLOW \
            --role ${{ secrets.AWS_ROLE_ARN }}
      - name: purge fastly cache url
        run: |
          node ./tools/scripts/fastly.js \
            --fastly-key ${{ secrets.FASTLY_PURGE_KEY }} \
            --env prod \
            --purge-internal
      - name: purge fastly cache url
        run: |
          node ./tools/scripts/fastly.js \
            --fastly-key ${{ secrets.FASTLY_PURGE_KEY }} \
            --env eu-prod \
            --purge-internal