name: Workers Test

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 3AM
    - cron: '0 4 * * *'

env:
  BUILD_NUMBER: event-${{ github.event.number }}-job-${{ github.run_number }}-attempt-${{ github.run_attempt }}

jobs:
  chrome:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    defaults:
      run:
        shell: bash

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: checkout and build
        uses: ./.github/actions/test-setup
      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b '*@*' -t 85000 tests/worker/**/*.test.js --concurrent=30
